name: "Rebecca's Cake Company"
favicon: null
layout_spectrum: 0.24855
typography_spectrum: 0.04817
title: "Rebecca's Cake Company"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A88D78'
    - '#4B2506'
    - '#000000'
    - '#DCD1C9'
    - '#DE9FB2'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
